### ISSUE TITLE
Lightning Terminal Showing red. Still not working after reinstalling package

### ISSUE THREAD

**Issue by godSaysHODL** [mynodebtc/mynode#763]
Logs are as follows:
`-- Logs begin at Wed 2023-04-12 04:30:11 CDT, end at Wed 2023-04-12 10:45:37 CDT. --
Apr 12 10:45:09 myNode systemd[1]: lit.service: Failed with result 'exit-code'.
Apr 12 10:45:09 myNode systemd[1]: lit.service: Main process exited, code=exited, status=1/FAILURE
Apr 12 10:45:09 myNode lit[15092]: context canceled
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.350 [DBG] GRPC: [core] Subchannel Connectivity change to SHUTDOWN
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.350 [DBG] GRPC: [core] Channel Connectivity change to SHUTDOWN
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.350 [DBG] GRPC: [core] Subchannel Connectivity change to SHUTDOWN
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.350 [DBG] GRPC: [core] Channel Connectivity change to SHUTDOWN
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.350 [DBG] GRPC: [core] Subchannel Connectivity change to SHUTDOWN
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.350 [DBG] GRPC: [core] Channel Connectivity change to SHUTDOWN
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.350 [DBG] LNDC: Lnd services finished
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.350 [DBG] LNDC: Wait for router to finish
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.350 [DBG] LNDC: Wait for invoices to finish
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.350 [DBG] LNDC: Wait for chain notifier to finish
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.350 [DBG] LNDC: Wait for client to finish
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.350 [DBG] GRPC: [core] Subchannel Connectivity change to SHUTDOWN
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.349 [DBG] GRPC: [core] Channel Connectivity change to SHUTDOWN
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.349 [DBG] LNDC: Closing lnd connection
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.348 [DBG] MBOX: Server connection closed
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.348 [DBG] MBOX: Server connection is closing
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.348 [DBG] MBOX: ServerConn: done creating gbn
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.348 [DBG] MBOX: Server: failed to re-create read stream mbox: rpc error: code = Canceled desc = context canceled
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.348 [DBG] MBOX: conn being closed
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.348 [DBG] MBOX: Server connection closed
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.348 [DBG] MBOX: Server connection is closing
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.348 [DBG] MBOX: ServerConn: done creating gbn
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.348 [DBG] MBOX: Server: failed to re-create read stream mbox: rpc error: code = Canceled desc = context canceled
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.347 [DBG] MBOX: conn being closed
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.347 [DBG] MBOX: Server connection closed
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.347 [DBG] MBOX: Server connection is closing
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.347 [DBG] MBOX: ServerConn: done creating gbn
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.347 [DBG] MBOX: Server: failed to re-create read stream mbox: rpc error: code = Canceled desc = context canceled
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.347 [DBG] MBOX: conn being closed
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.347 [DBG] MBOX: Server connection closed
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.347 [DBG] MBOX: Server connection is closing
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.347 [DBG] MBOX: ServerConn: done creating gbn
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.347 [DBG] MBOX: Server: failed to re-create read stream mbox: rpc error: code = Canceled desc = context canceled
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.346 [DBG] MBOX: conn being closed
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.346 [DBG] MBOX: Server connection closed
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.346 [DBG] MBOX: Server connection is closing
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.346 [DBG] MBOX: ServerConn: done creating gbn
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.346 [DBG] MBOX: Server: failed to re-create read stream mbox: rpc error: code = Canceled desc = context canceled
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.346 [DBG] MBOX: conn being closed
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.346 [DBG] MBOX: Server connection closed
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.346 [DBG] MBOX: Server connection is closing
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.346 [DBG] MBOX: ServerConn: done creating gbn
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.346 [DBG] MBOX: Server: failed to re-create read stream mbox: rpc error: code = Canceled desc = context canceled
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.346 [DBG] MBOX: conn being closed
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.345 [DBG] MBOX: Server connection closed
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.345 [DBG] MBOX: Server connection is closing
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.345 [DBG] MBOX: Server: failed to re-create read stream mbox: rpc error: code = Canceled desc = context canceled
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.345 [DBG] MBOX: ServerConn: done creating gbn
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.345 [DBG] MBOX: conn being closed
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.345 [ERR] LITD: Could not start subservers: context canceled
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.345 [ERR] LNDC: Could not receive from interceptor stream: rpc error: code = Unknown desc = RPC middleware not enabled in config
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.342 [INF] LITD: Starting LiT middleware manager
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.319 [DBG] MBOX: ServerConn: creating gbn, waiting for sync
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.319 [INF] LITD: Starting LiT account service
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.319 [DBG] LITD: Not resuming session 03ed091b0cccd2e3ad6439e3f27dd50d6fab0db51db0ad36b1468245a2a6fa9009 with state 2
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.319 [DBG] LITD: Not resuming session 03d57f954bebfc44294b58626f6dd7bd95d278a5d9adca33a764728f7ad9e5600e with state 2
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.319 [DBG] LITD: Not resuming session 03d21b7e88d4bcee93fb1c9ba55e40012448f453286c7463092a6067372d4e0169 with state 2
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.319 [DBG] LITD: Not resuming session 03c6ae0c2631ec25f06e26d8e68ffcc1902ddf101f4064ab12f92954a685863749 with state 2
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.318 [DBG] LITD: Not resuming session 03bd7b889c8b695ba68f50dd9c728ebf769a6fdd261128ecb4f8a88f6986067416 with state 2
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.318 [INF] SESS: Mailbox RPC server listening on mailbox:0678bfdb0969c019e4474e812af8ef30de35c9157a124cd538aaeca83bf8b7a5475870d268c1083a7f97941d552e0b5afd6878914bcbc6bdb52de170665c4bdd@mailbox.terminal.lightning.today:443
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.317 [DBG] GRPC: [core] Channel Connectivity change to CONNECTING
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.317 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x4000908c80, {CONNECTING }
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.317 [DBG] GRPC: [core] Subchannel picks a new address "mailbox.terminal.lightning.today:443" to connect
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.317 [DBG] GRPC: [core] Subchannel Connectivity change to CONNECTING
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.317 [DBG] GRPC: [core] Channel switches to new LB policy "pick_first"
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.316 [DBG] GRPC: [core] ClientConn switching balancer to "pick_first"
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.316 [DBG] GRPC: [core] ccResolverWrapper: sending update to cc: {[{mailbox.terminal.lightning.today:443   0 }]  }
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.316 [DBG] GRPC: [core] scheme "" not registered, fallback to default scheme
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.316 [DBG] GRPC: [core] parsed scheme: ""
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.314 [DBG] MBOX: ServerConn: creating gbn, waiting for sync
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.312 [DBG] LITD: Not resuming session 0372313c120f22a1aa39f95b7536a981c4a4df4a9b7d85160c7a71dd33965153b4 with state 2
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.312 [DBG] LITD: Not resuming session 0356d236f58ee6648c3edb7df0b84fa916d4eaa919afadf1310893362e7738246f with state 2
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.312 [DBG] LITD: Not resuming session 0346a36573ee08ff3724806f8d6a9f194f144f69fe1de3eada295570d103997ca5 with state 2
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.312 [DBG] LITD: Not resuming session 0343c36452c19b761f0ce4387bdb474f09ca8428f29aca70ab529afd2001064cdf with state 2
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.312 [DBG] LITD: Not resuming session 032f039f0e410f99f06d742fa5b1fa91653f3d752abeea9043905d351756f74fae with state 2
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.311 [DBG] LITD: Not resuming session 031c8d2c50d3263b4917c65b54a49664381f06cf133fdb7c8ac2dfb4323c059fb5 with state 2
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.311 [INF] SESS: Mailbox RPC server listening on mailbox:79b1959917ec1ccf2d67ad638eddadbd7ba1c87dd0176ba4566149bd4232b6ad996c20f2495ab8501d072a2d055eddbf475bbff459814fce0b38fa3761b29814@mailbox.terminal.lightning.today:443
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.311 [DBG] GRPC: [core] Subchannel picks a new address "mailbox.terminal.lightning.today:443" to connect
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.311 [DBG] GRPC: [core] Channel Connectivity change to CONNECTING
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.311 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x40009088b0, {CONNECTING }
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.310 [DBG] GRPC: [core] Subchannel Connectivity change to CONNECTING
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.310 [DBG] GRPC: [core] Channel switches to new LB policy "pick_first"
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.310 [DBG] GRPC: [core] ClientConn switching balancer to "pick_first"
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.310 [DBG] GRPC: [core] ccResolverWrapper: sending update to cc: {[{mailbox.terminal.lightning.today:443   0 }]  }
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.310 [DBG] GRPC: [core] scheme "" not registered, fallback to default scheme
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.309 [DBG] GRPC: [core] parsed scheme: ""
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.308 [DBG] MBOX: ServerConn: creating gbn, waiting for sync
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.305 [INF] SESS: Mailbox RPC server listening on mailbox:bbc9e45bbb6b139c2e4de1652b8ca096621f1aa62a1bbdc00cb9cffcdf411ac975e47cde195407b6fd360a922924432ea391e0cd376e22a1383a0677ab988a8b@mailbox.terminal.lightning.today:443
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.305 [DBG] LITD: Not resuming session 030a629f6e7bfd9c3a117ffab29d12fb3107717dad53965bfedcc54b983b454549 with state 2
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.305 [DBG] LITD: Not resuming session 02c83d5825bc88e041bf490eb1ae895148b1846c324d832ca22084c994aa6f95b0 with state 2
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.304 [DBG] GRPC: [core] Subchannel picks a new address "mailbox.terminal.lightning.today:443" to connect
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.304 [DBG] GRPC: [core] Channel Connectivity change to CONNECTING
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.304 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x4000b02660, {CONNECTING }
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.304 [DBG] GRPC: [core] Subchannel Connectivity change to CONNECTING
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.304 [DBG] GRPC: [core] Channel switches to new LB policy "pick_first"
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.304 [DBG] GRPC: [core] ClientConn switching balancer to "pick_first"
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.304 [DBG] GRPC: [core] ccResolverWrapper: sending update to cc: {[{mailbox.terminal.lightning.today:443   0 }]  }
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.303 [DBG] GRPC: [core] scheme "" not registered, fallback to default scheme
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.303 [DBG] GRPC: [core] parsed scheme: ""
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.303 [DBG] MBOX: ServerConn: creating gbn, waiting for sync
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.300 [INF] SESS: Mailbox RPC server listening on mailbox:426c15e7dca8937af77dde3d1cac2f588d5ccac19117d469d05c295d33cd9591158e117e3b5fbc505554d52632a9fe18003a3179ae53faae0b936e7b725fdbc9@mailbox.terminal.lightning.today:443
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.300 [DBG] LITD: Not resuming session 02b90a073a67aad3c37e28b4cee064c1424fad08a9b262ca51b76b1f01aa450537 with state 2
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.300 [DBG] LITD: Not resuming session 02b3189fc623d78e86403a210ce2d09d83a111f128d4fca393c7ac75ead7a415a5 with state 2
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.300 [DBG] GRPC: [core] Subchannel picks a new address "mailbox.terminal.lightning.today:443" to connect
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.300 [DBG] GRPC: [core] Channel Connectivity change to CONNECTING
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.300 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x4000b022b0, {CONNECTING }
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.299 [DBG] GRPC: [core] Subchannel Connectivity change to CONNECTING
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.299 [DBG] GRPC: [core] Channel switches to new LB policy "pick_first"
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.299 [DBG] GRPC: [core] ClientConn switching balancer to "pick_first"
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.299 [DBG] GRPC: [core] ccResolverWrapper: sending update to cc: {[{mailbox.terminal.lightning.today:443   0 }]  }
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.299 [DBG] GRPC: [core] scheme "" not registered, fallback to default scheme
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.299 [DBG] GRPC: [core] parsed scheme: ""
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.297 [DBG] MBOX: ServerConn: creating gbn, waiting for sync
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.296 [DBG] GRPC: [core] Subchannel picks a new address "mailbox.terminal.lightning.today:443" to connect
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.296 [INF] SESS: Mailbox RPC server listening on mailbox:34a175fc3899fc826a7f3bfa885962a5584723ff82e5ba9fff895abc07d2a97565bc116817e4c74925135310791e5d6fefeaf8497e2c834a191a040673c80ce1@mailbox.terminal.lightning.today:443
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.296 [DBG] GRPC: [core] Channel Connectivity change to CONNECTING
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.296 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x4000860270, {CONNECTING }
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.295 [DBG] GRPC: [core] Subchannel Connectivity change to CONNECTING
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.294 [DBG] GRPC: [core] Channel switches to new LB policy "pick_first"
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.294 [DBG] GRPC: [core] ClientConn switching balancer to "pick_first"
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.294 [DBG] GRPC: [core] ccResolverWrapper: sending update to cc: {[{mailbox.terminal.lightning.today:443   0 }]  }
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.294 [DBG] GRPC: [core] scheme "" not registered, fallback to default scheme
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.294 [DBG] GRPC: [core] parsed scheme: ""
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.292 [DBG] MBOX: ServerConn: creating gbn, waiting for sync
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.291 [INF] SESS: Mailbox RPC server listening on mailbox:ed08269877929dbd8cce293c4af439046343ec2fb5a3b61929f3d8296411c3510f8ff6e94180dfbfe0d3cab8495a5826b7ae5cb09c4af31e1cc6d81bf572479b@mailbox.terminal.lightning.today:443
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.290 [DBG] GRPC: [core] Subchannel picks a new address "mailbox.terminal.lightning.today:443" to connect
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.290 [DBG] GRPC: [core] Channel Connectivity change to CONNECTING
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.290 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x4000860db0, {CONNECTING }
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.290 [DBG] GRPC: [core] Subchannel Connectivity change to CONNECTING
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.289 [DBG] GRPC: [core] Channel switches to new LB policy "pick_first"
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.289 [DBG] GRPC: [core] ClientConn switching balancer to "pick_first"
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.289 [DBG] GRPC: [core] ccResolverWrapper: sending update to cc: {[{mailbox.terminal.lightning.today:443   0 }]  }
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.289 [DBG] GRPC: [core] scheme "" not registered, fallback to default scheme
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.289 [DBG] GRPC: [core] parsed scheme: ""
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.286 [DBG] MBOX: ServerConn: creating gbn, waiting for sync
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.284 [INF] SESS: Mailbox RPC server listening on mailbox:6e2247acdedd6e7368a92c6347c98046442d450554bf5357869399a8a698aa486b61673b52a596da2dd6429dce96037324066861508a43180331869894501c79@mailbox.terminal.lightning.today:443
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.284 [DBG] LITD: Not resuming session 02906799ecfcd06c4771f183196b0740919d0302e55e72a5808ccd6a589ad59120 with state 2
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.284 [DBG] LITD: Not resuming session 027d7b17f7f4f55fdcc5a2e10091338e7f787766f793a2bfcc5f7659bc281cc9a9 with state 2
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.283 [DBG] GRPC: [core] Subchannel picks a new address "mailbox.terminal.lightning.today:443" to connect
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.283 [DBG] GRPC: [core] Channel Connectivity change to CONNECTING
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.283 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x4000860c90, {CONNECTING }
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.282 [DBG] GRPC: [core] Subchannel Connectivity change to CONNECTING
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.282 [DBG] GRPC: [core] Channel switches to new LB policy "pick_first"
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.282 [DBG] GRPC: [core] ClientConn switching balancer to "pick_first"
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.282 [DBG] GRPC: [core] ccResolverWrapper: sending update to cc: {[{mailbox.terminal.lightning.today:443   0 }]  }
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.282 [DBG] GRPC: [core] scheme "" not registered, fallback to default scheme
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.282 [DBG] GRPC: [core] parsed scheme: ""
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.278 [DBG] LITD: Not resuming session 0251ad18f2f17d2eef7c2e3a7cd7d232363deaf2155f196251c08eafbbddedf0e4 with state 2
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.277 [DBG] LITD: Not resuming session 023d7fb5b44a09d34054b1bb87534a3df10acbc595a2f2893b0525ad0f6f34ae2f with state 2
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.277 [DBG] LITD: Not resuming session 0228ee52cb1b0881cf7c9a1ce65fee5dc2837f17aaeea879668af58622b6ca9794 with state 2
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.270 [DBG] GRPC: [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.270 [INF] LITD: Starting LiT session server
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.270 [DBG] GRPC: [core] Subchannel Connectivity change to SHUTDOWN
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.270 [DBG] GRPC: [core] Channel Connectivity change to SHUTDOWN
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.222 [DBG] GRPC: [core] Channel Connectivity change to READY
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.222 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x4000860190, {READY }
Apr 12 10:45:09 myNode lit[15092]: 2023-04-12 10:45:09.222 [DBG] GRPC: [core] Subchannel Connectivity change to READY
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.958 [DBG] GRPC: [core] Subchannel picks a new address "autopilot.lightning.finance:12010" to connect
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.957 [DBG] GRPC: [core] Channel Connectivity change to CONNECTING
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.957 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x4000860190, {CONNECTING }
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.957 [DBG] GRPC: [core] blockingPicker: the picked transport is not ready, loop back to repick
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.957 [DBG] GRPC: [core] Subchannel Connectivity change to CONNECTING
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.957 [DBG] GRPC: [core] Channel switches to new LB policy "pick_first"
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.957 [DBG] GRPC: [core] ClientConn switching balancer to "pick_first"
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.956 [DBG] GRPC: [core] ccResolverWrapper: sending update to cc: {[{autopilot.lightning.finance:12010   0 }]  }
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.956 [DBG] GRPC: [core] scheme "" not registered, fallback to default scheme
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.956 [DBG] GRPC: [core] parsed scheme: ""
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.956 [INF] AUTO: Starting Autopilot Client
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.781 [INF] LITD: Starting LiT macaroon service
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.617 [INF] LITD: Starting integrated faraday daemon
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.616 [INF] LNDC: lnd is now fully synced to its chain backend
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.595 [INF] LNDC: Waiting for lnd to be fully synced to its chain backend, this might take a while
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.595 [INF] LNDC: Using network mainnet
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.595 [INF] LNDC: lnd version: v0.16.0-beta, build tags 'autopilotrpc,signrpc,walletrpc,chainrpc,invoicesrpc,watchtowerrpc,neutrinorpc,monitoring,peersrpc,kvdb_postgres,kvdb_etcd,kvdb_sqlite'
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.568 [DBG] GRPC: [core] Channel Connectivity change to READY
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.568 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x4000860a60, {READY }
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.568 [DBG] GRPC: [core] Subchannel Connectivity change to READY
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.563 [INF] LNDC: Wallet state of lnd is now: Lnd main server is ready for requests
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.562 [INF] LNDC: Waiting for lnd to unlock
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.562 [DBG] GRPC: [core] Channel Connectivity change to READY
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.562 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x4000663980, {READY }
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.562 [DBG] GRPC: [core] Subchannel Connectivity change to READY
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.556 [DBG] GRPC: [core] Subchannel picks a new address "localhost:10009" to connect
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.556 [INF] LNDC: Connected to lnd
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.556 [DBG] GRPC: [core] Channel Connectivity change to CONNECTING
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.556 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x4000663980, {CONNECTING }
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.556 [DBG] GRPC: [core] Subchannel Connectivity change to CONNECTING
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.556 [DBG] GRPC: [core] Channel Connectivity change to CONNECTING
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.555 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x4000860a60, {CONNECTING }
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.556 [DBG] GRPC: [core] Channel switches to new LB policy "pick_first"
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.556 [DBG] GRPC: [core] ClientConn switching balancer to "pick_first"
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.556 [DBG] GRPC: [core] ccResolverWrapper: sending update to cc: {[{localhost:10009   0 }]  }
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.556 [DBG] GRPC: [core] scheme "" not registered, fallback to default scheme
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.555 [DBG] GRPC: [core] parsed scheme: ""
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.555 [DBG] GRPC: [core] Subchannel picks a new address "localhost:10009" to connect
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.555 [INF] LNDC: Creating lnd connection to localhost:10009
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.555 [INF] LITD: Connecting full lnd client
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.555 [DBG] GRPC: [core] Subchannel Connectivity change to CONNECTING
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.554 [DBG] GRPC: [core] Channel switches to new LB policy "pick_first"
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.554 [DBG] GRPC: [core] ClientConn switching balancer to "pick_first"
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.554 [DBG] GRPC: [core] ccResolverWrapper: sending update to cc: {[{localhost:10009   0 }]  }
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.554 [DBG] GRPC: [core] scheme "" not registered, fallback to default scheme
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.554 [DBG] GRPC: [core] parsed scheme: ""
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.352 [INF] LITD: Connecting basic lnd client
Apr 12 10:45:08 myNode lit[15092]: ----------------------------------------------------------
Apr 12 10:45:08 myNode lit[15092]:  Web interface           0.0.0.0:8443 (open https://localhost:8443 in your browser)
Apr 12 10:45:08 myNode lit[15092]:  LiT Version             0.9.0-alpha commit=v0.9.0-alpha
Apr 12 10:45:08 myNode lit[15092]:  LND Version             0.16.0-beta commit=v0.16.0-beta
Apr 12 10:45:08 myNode lit[15092]:  LND Alias               Variable Fate
Apr 12 10:45:08 myNode lit[15092]:  LND Node status         online
Apr 12 10:45:08 myNode lit[15092]:  LND Operating mode      remote
Apr 12 10:45:08 myNode lit[15092]:                                                           
Apr 12 10:45:08 myNode lit[15092]:  Lightning Terminal (LiT) by Lightning Labs
Apr 12 10:45:08 myNode lit[15092]: ----------------------------------------------------------
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.327 [DBG] GRPC: [core] Channel Connectivity change to READY
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.326 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x40005794e0, {READY }
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.326 [DBG] GRPC: [core] Subchannel Connectivity change to READY
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.323 [DBG] GRPC: [core] Channel Connectivity change to READY
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.322 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x40005b8ea0, {READY }
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.319 [DBG] GRPC: [core] Subchannel Connectivity change to READY
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.321 [DBG] GRPC: [core] Channel Connectivity change to READY
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.320 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x40005781c0, {READY }
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.320 [DBG] GRPC: [core] Subchannel Connectivity change to READY
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.318 [DBG] GRPC: [core] Channel Connectivity change to READY
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.318 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x4000578530, {READY }
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.318 [DBG] GRPC: [core] Subchannel Connectivity change to READY
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.316 [DBG] GRPC: [core] Subchannel picks a new address "localhost:10009" to connect
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.316 [DBG] GRPC: [core] Channel Connectivity change to CONNECTING
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.316 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x40005794e0, {CONNECTING }
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.316 [DBG] GRPC: [core] blockingPicker: the picked transport is not ready, loop back to repick
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.316 [DBG] GRPC: [core] Subchannel Connectivity change to CONNECTING
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.316 [DBG] GRPC: [core] Channel switches to new LB policy "pick_first"
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.316 [DBG] GRPC: [core] ClientConn switching balancer to "pick_first"
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.316 [DBG] GRPC: [core] ccResolverWrapper: sending update to cc: {[{localhost:10009   0 }]  }
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.315 [DBG] GRPC: [core] scheme "" not registered, fallback to default scheme
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.315 [DBG] GRPC: [core] parsed scheme: ""
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.313 [INF] LITD: Listening for http_tls on: [::]:8443
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.312 [DBG] GRPC: [core] Subchannel picks a new address "localhost:12010" to connect
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.311 [DBG] GRPC: [core] Channel Connectivity change to CONNECTING
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.311 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x4000578530, {CONNECTING }
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.311 [DBG] GRPC: [core] Subchannel Connectivity change to CONNECTING
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.310 [DBG] GRPC: [core] Channel switches to new LB policy "pick_first"
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.310 [DBG] GRPC: [core] ClientConn switching balancer to "pick_first"
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.310 [DBG] GRPC: [core] ccResolverWrapper: sending update to cc: {[{localhost:12010   0 }]  }
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.310 [DBG] GRPC: [core] scheme "" not registered, fallback to default scheme
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.310 [DBG] GRPC: [core] parsed scheme: ""
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.308 [DBG] GRPC: [core] Subchannel picks a new address "localhost:11010" to connect
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.308 [INF] LITD: Dialing pool gRPC server at localhost:12010
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.308 [DBG] GRPC: [core] Channel Connectivity change to CONNECTING
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.308 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x40005781c0, {CONNECTING }
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.307 [DBG] GRPC: [core] Subchannel Connectivity change to CONNECTING
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.307 [DBG] GRPC: [core] Channel switches to new LB policy "pick_first"
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.307 [DBG] GRPC: [core] ClientConn switching balancer to "pick_first"
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.307 [DBG] GRPC: [core] ccResolverWrapper: sending update to cc: {[{localhost:11010   0 }]  }
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.307 [DBG] GRPC: [core] scheme "" not registered, fallback to default scheme
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.307 [DBG] GRPC: [core] parsed scheme: ""
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.306 [INF] LITD: Dialing loop gRPC server at localhost:11010
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.306 [DBG] GRPC: [core] Channel Connectivity change to CONNECTING
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.306 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x40005b8ea0, {CONNECTING }
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.306 [DBG] GRPC: [core] Subchannel picks a new address "localhost:10009" to connect
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.306 [DBG] GRPC: [core] Subchannel Connectivity change to CONNECTING
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.306 [DBG] GRPC: [core] Channel switches to new LB policy "pick_first"
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.306 [DBG] GRPC: [core] ClientConn switching balancer to "pick_first"
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.306 [DBG] GRPC: [core] ccResolverWrapper: sending update to cc: {[{localhost:10009   0 }]  }
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.306 [DBG] GRPC: [core] scheme "" not registered, fallback to default scheme
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.305 [DBG] GRPC: [core] parsed scheme: ""
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.305 [INF] LITD: Dialing lnd gRPC server at localhost:10009
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.305 [INF] SESS: Checking for schema update: latest_version=0, db_version=0
Apr 12 10:45:08 myNode lit[15092]: 2023-04-12 10:45:08.300 [INF] LITD: LiT version: 0.9.0-alpha commit=v0.9.0-alpha
Apr 12 10:45:08 myNode systemd[1]: Started Lightning Terminal.
Apr 12 10:45:08 myNode lit[15062]: LND is ready.
Apr 12 10:45:08 myNode lit[15062]:     "synced_to_chain": true,
Apr 12 10:45:08 myNode lit[15062]: Checking if LND is synced...
Apr 12 10:45:07 myNode lit[15060]: + exit 0
Apr 12 10:45:07 myNode lit[15060]: }
Apr 12 10:45:07 myNode lit[15060]:   "warnings": ""
Apr 12 10:45:07 myNode lit[15060]:   "pruned": false,
Apr 12 10:45:07 myNode lit[15060]:   "size_on_disk": 536504806069,
Apr 12 10:45:07 myNode lit[15060]:   "chainwork": "0000000000000000000000000000000000000000455eb3a30204414fa0667894",
Apr 12 10:45:07 myNode lit[15060]:   "initialblockdownload": false,
Apr 12 10:45:07 myNode lit[15060]:   "verificationprogress": 0.9999995096169555,
Apr 12 10:45:07 myNode lit[15060]:   "mediantime": 1681311511,
Apr 12 10:45:07 myNode lit[15060]:   "time": 1681314169,
Apr 12 10:45:07 myNode lit[15060]:   "difficulty": 47887764338536.25,
Apr 12 10:45:07 myNode lit[15060]:   "bestblockhash": "000000000000000000035e95d598779668af4fcc8b7d00812d97596c4c30dab2",
Apr 12 10:45:07 myNode lit[15060]:   "headers": 785096,
Apr 12 10:45:07 myNode lit[15060]:   "blocks": 785096,
Apr 12 10:45:07 myNode lit[15060]:   "chain": "main",
Apr 12 10:45:07 myNode lit[15060]: {
Apr 12 10:45:07 myNode lit[15060]: + bitcoin-cli -datadir=/mnt/hdd/mynode/bitcoin -rpcwait getblockchaininfo
Apr 12 10:45:07 myNode lit[15060]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoin_synced ']'
Apr 12 10:45:07 myNode lit[15060]: Checking if Bitcoin is synced...
Apr 12 10:45:07 myNode lit[15060]: + echo 'Checking if Bitcoin is synced...'
Apr 12 10:45:07 myNode lit[15060]: + set -e
Apr 12 10:45:07 myNode lit[15058]: Not shutting down!
Apr 12 10:45:07 myNode lit[15058]: Checking if device is shutting down...`

**Comment by Eegee** [comment]
For me as well.
In my situation it might have something to do with permissions as I'm seeing ```[INF] INVC: Cancelling invoice subscription for client=8
[ERR] RPCS: [/lnrpc.Lightning/RegisterRPCMiddleware]: permission denied
[INF] INVC: New invoice subscription client: id=8``` in the LND log
and `LNDC: Could not receive from interceptor stream: rpc error: code = Unknown desc = permission denied` in the Lightning Terminal log.

I have the rpc middleware enabled in [lnd.conf], from commit https://github.com/mynodebtc/mynode/commit/12057af24a0743d2b837fd40e1b4466348b90459

How to grant permission for the RPC Middleware and Lightning Terminal?

**Comment by tehelsper** [comment]
@godSaysHODL It looks like you probably have a custom LND that isn't compatible with the latest software versions.

@Eegee I've not seen that error before. Did it just start with the latest version?

**Comment by Eegee** [comment]
> @Eegee I've not seen that error before. Did it just start with the latest version?
Yes, it did. My node is on v0.3.14 and came from v0.3.12.

**Comment by HamishMacEwan** [comment]
The error I have since upgrading to v0.3.14 is (in reverse time order):

```
Apr 19 14:43:00 myNode lit[20297]: 2023-04-19 14:43:00.809 [DBG] LNDC: Lnd services finished
Apr 19 14:43:00 myNode lit[20297]: 2023-04-19 14:43:00.809 [DBG] LNDC: Wait for router to finish
Apr 19 14:43:00 myNode lit[20297]: 2023-04-19 14:43:00.809 [DBG] LNDC: Wait for invoices to finish
Apr 19 14:43:00 myNode lit[20297]: 2023-04-19 14:43:00.809 [DBG] LNDC: Wait for chain notifier to finish
Apr 19 14:43:00 myNode lit[20297]: 2023-04-19 14:43:00.809 [DBG] LNDC: Wait for client to finish
Apr 19 14:43:00 myNode lit[20297]: 2023-04-19 14:43:00.809 [DBG] GRPC: [core] Subchannel Connectivity change to SHUTDOWN
Apr 19 14:43:00 myNode lit[20297]: 2023-04-19 14:43:00.809 [DBG] GRPC: [core] Channel Connectivity change to SHUTDOWN
Apr 19 14:43:00 myNode lit[20297]: 2023-04-19 14:43:00.809 [DBG] LNDC: Closing lnd connection
Apr 19 14:43:00 myNode lit[20297]: 2023-04-19 14:43:00.807 [ERR] LNDC: Could not receive from interceptor stream: rpc error: code = Unknown desc = permission denied
Apr 19 14:43:00 myNode lit[20297]: 2023-04-19 14:43:00.808 [ERR] LITD: Could not start subservers: context canceled
Apr 19 14:43:00 myNode lit[20297]: 2023-04-19 14:43:00.802 [INF] LITD: Starting LiT middleware manager
Apr 19 14:43:00 myNode lit[20297]: 2023-04-19 14:43:00.763 [INF] LITD: Starting LiT account service
Apr 19 14:43:00 myNode lit[20297]: 2023-04-19 14:43:00.762 [DBG] LITD: Not resuming session 020ea079c59bbb55b57b1a9b5bca7cb19b687fabd7491729cafcd32e61bba7eac5 with type 3
Apr 19 14:43:00 myNode lit[20297]: 2023-04-19 14:43:00.762 [DBG] LITD: Not resuming session 020080985c79f183e027b922a7141b7683bf4799eb13df6b95a53b625ba7bb776f. Could not bake the necessary macaroon: %!w(*status.Error=&{0x40008987e0})
Apr 19 14:43:00 myNode lit[20297]: 2023-04-19 14:43:00.748 [DBG] GRPC: [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
Apr 19 14:43:00 myNode lit[20297]: 2023-04-19 14:43:00.748 [INF] LITD: Starting LiT session server
```

Everything else is working fine.

If a custom LND configuration is missing a required element for `lit.service` what might it be?

Currently lnd.config contains:

```
# This line needs to be uncommented if you have a lnd wallet and commented if you do not
wallet-unlock-password-file=/mnt/hdd/mynode/settings/.lndpw
wallet-unlock-allow-create=true
```

Which has been the most recommended configuration change for other errors.

Given the new customisation option and the length of time and number of tweaks I've made, perhaps it is time to reset the config…  But I would like to understand what the error is and how it arose.

**Comment by MWDJ** [comment]
I've have the same problem as well. 
This started with my attempts to custom upgrade to 0.8.6-alpha.  I always reverted back to 0.8.5-alpha and restored capability.  After upgrading to myNode 0.3.15 from 0.3.13 I've had the same repeated crashes of LiT. I haven't been able to connect with a pairing phrase for months now.  (So I'm certain there's a macaroon issue somewhere)

Manual inspection of the lit.conf all appeared OK.

I also corrected the custom LND conf per the LiT Remote requirements: 
tlsextraip=<externally-reachable-ip-address>
rpclisten=0.0.0.0:10009
rpcmiddleware.enable=true

LiT still shuts down, here are the log entries with 0.9.0-alpha: (reverse order)

Apr 22 16:02:19 myNode lit[15728]: 2023-04-22 16:02:19.107 [DBG] LNDC: Lnd services finished
Apr 22 16:02:19 myNode lit[15728]: 2023-04-22 16:02:19.107 [DBG] LNDC: Wait for router to finish
Apr 22 16:02:19 myNode lit[15728]: 2023-04-22 16:02:19.107 [DBG] LNDC: Wait for invoices to finish
Apr 22 16:02:19 myNode lit[15728]: 2023-04-22 16:02:19.106 [DBG] LNDC: Wait for chain notifier to finish
Apr 22 16:02:19 myNode lit[15728]: 2023-04-22 16:02:19.106 [DBG] LNDC: Wait for client to finish
Apr 22 16:02:19 myNode lit[15728]: 2023-04-22 16:02:19.106 [DBG] GRPC: [core] Subchannel Connectivity change to SHUTDOWN
Apr 22 16:02:19 myNode lit[15728]: 2023-04-22 16:02:19.106 [DBG] GRPC: [core] Channel Connectivity change to SHUTDOWN
Apr 22 16:02:19 myNode lit[15728]: 2023-04-22 16:02:19.106 [DBG] LNDC: Closing lnd connection
Apr 22 16:02:19 myNode lit[15728]: 2023-04-22 16:02:19.105 [ERR] LITD: Could not start subservers: context canceled
Apr 22 16:02:19 myNode lit[15728]: 2023-04-22 16:02:19.104 [ERR] LNDC: Could not receive from interceptor stream: rpc error: code = Unknown desc = permission denied
Apr 22 16:02:19 myNode lit[15728]: 2023-04-22 16:02:19.102 [INF] LITD: Starting LiT middleware manager
Apr 22 16:02:18 myNode lit[15728]: 2023-04-22 16:02:18.980 [DBG] GRPC: [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
Apr 22 16:02:18 myNode lit[15728]: 2023-04-22 16:02:18.980 [INF] LITD: Starting LiT account service
Apr 22 16:02:18 myNode lit[15728]: 2023-04-22 16:02:18.980 [INF] LITD: Starting LiT session server
Apr 22 16:02:18 myNode lit[15728]: 2023-04-22 16:02:18.980 [DBG] GRPC: [core] Subchannel Connectivity change to SHUTDOWN
Apr 22 16:02:18 myNode lit[15728]: 2023-04-22 16:02:18.980 [DBG] GRPC: [core] Channel Connectivity change to SHUTDOWN
Apr 22 16:02:18 myNode lit[15728]: 2023-04-22 16:02:18.917 [DBG] GRPC: [core] Channel Connectivity change to READY

Also, before clearing the custom bitcoin version, upgrade script could not finish, and the LiT version was listed as "unknown" - attempts to downgrade back to 0.8.5-alpha failed.  After clearing the custom bitcoin version, "unknown" went away and now reports 0.9.0-alpha.

I will keep experimenting; hopefully will get something working.  Considering just completely reinstalling myNode from a fresh SD card image.

-DJ

**Comment by MWDJ** [comment]
I have restored functionality by reverting to 0.8.5-alpha, but I'm sure this is temporary.

**Comment by tehelsper** [comment]
Does LiT actually work when rpcmiddleware has been disabled? I was under the impression it was necessary to connect to the remote lnd instance.

Also, when LiT was running into the above error, was LND up and running properly? I don't fully understand the log messages, but it appears to be some sort of communication issue between lit and lnd.

The "unknown" version means it did not install and if you had a custom bitcoin version failing first, that would explain the unknown version.

**Comment by Eegee** [comment]
I entirely disabled LiT last week to get 'rid' of the red dot, but I just tried your suggestion.
> Does LiT actually work when rpcmiddleware has been disabled?

To try this I enabled it again, but first changed rpcmiddleware.enable to false in lnd.conf, rebooted and waited for LND to properly run.
Unfortunately I'm still getting `RPCS: [/lnrpc.Lightning/RegisterRPCMiddleware]: permission denied` in the LND log and `[ERR] LNDC: Could not receive from interceptor stream: rpc error: code = Unknown desc = permission denied` in the Terminal log.
So as far as I can tell disabling rpcmiddleware didn't make a difference.
I haven't done anything with the macaroons yet btw.

**Comment by MWDJ** [comment]
> Does LiT actually work when rpcmiddleware has been disabled? I was under the impression it was necessary to connect to the remote lnd instance.
> 
Yes LiT works using the lit.conf flag "rpcmiddleware.disabled=true" or "--rpcmiddleware.disabled" from the command line... At least enough to operate pool, loop, and channel services through the Lightning Terminal interface.

When disabled, I do not have any grpc access denied messages.  Thanks for the follow up.  

Here's myNode lit.conf (unmodified) that fails:  
(To make LiT work, I just added the rpcmiddleware.disabled=true to a custom lit2.conf and referenced this file from the command line)  It appears that myNode LiTd service scheduler overwrites any changes I make to lit.conf.

#######################################
# Application Options
#######################################
httpslisten=0.0.0.0:8443
uipassword_file=/mnt/hdd/mynode/settings/.litpw
lit-dir=/mnt/hdd/mynode/lit

network=mainnet

lnd-mode=remote
loop-mode=remote
pool-mode=remote

# Remote options
remote.lit-debuglevel=debug

# Remote lnd options
remote.lnd.rpcserver=localhost:10009
remote.lnd.macaroonpath=/mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/admin.macaroon
remote.lnd.tlscertpath=/mnt/hdd/mynode/lnd/tls.cert

# Remote loop options
remote.loop.rpcserver=localhost:11010
remote.loop.macaroonpath=/mnt/hdd/mynode/loop/mainnet/loop.macaroon
remote.loop.tlscertpath=/mnt/hdd/mynode/loop/mainnet/tls.cert

# Remote pool options
remote.pool.rpcserver=localhost:12010
remote.pool.macaroonpath=/mnt/hdd/mynode/pool/mainnet/pool.macaroon
remote.pool.tlscertpath=/mnt/hdd/mynode/pool/mainnet/tls.cert

#######################################
# Loop
#######################################
#loop.loopdir=/mnt/hdd/mynode/loop
#loop.loopoutmaxparts=5

#######################################
# Pool
#######################################
#pool.basedir=/mnt/hdd/mynode/pool
#pool.newnodesonly=true

#######################################
# Faraday
#######################################
faraday.faradaydir=/mnt/hdd/mynode/faraday
faraday.min_monitored=48h

# Faraday - bitcoin
faraday.connect_bitcoin=true
faraday.bitcoin.host=localhost
faraday.bitcoin.user=mynode
faraday.bitcoin.password=password

#######################################
# LND - STILL USING REMOTE NODE FOR NOW
#######################################
# lnd.maxpendingchannels=5
# lnd.alias=myNode [LND]
# lnd.color=#68F442

# # Tor-only by default
# lnd.listen=localhost

# lnd.rpclisten=0.0.0.0:10009
# lnd.restlisten=0.0.0.0:10080

# lnd.tlsextraip=0.0.0.0
# lnd.tlsextradomain=mynode.local

# lnd.debuglevel=info
# #lnd.debuglevel=debug

# lnd.ignore-historical-gossip-filters=true
# lnd.accept-keysend=true
# lnd.caches.channel-cache-size=35000

# lnd.bitcoin.active=1
# lnd.bitcoin.mainnet=1
# lnd.bitcoin.node=bitcoind

# lnd.bitcoind.rpchost=127.0.0.1:8332

# #lnd.autopilot.active=1
# #lnd.autopilot.maxchannels=5
# #lnd.autopilot.allocation=0.6

-DJ

**Comment by Eegee** [comment]
FYI I've now tried deleting the `admin.macaroon`, `readonly.macaroon` and `invoice.macaroon` from `/mnt/hdd/mynode/lnd/data/chain/bitcoin` (@HamishMacEwan not from the ~/.lnd/ folder, but this folder) and restarting lnd (actually rebooted entire Rpi) and this fixed the problem for me.

Checking the differences, new in admin.macaroon is `macaroon generate read write` (was only `macaroon generate`) and new in invoice.macaroon is an added line `maracoon read` below the line `invoices read`.

**Comment by tehelsper** [comment]
@Eegee Wow, thanks for that link. That may be the root cause for some of these issues. It's been a long time, but pre-0.9.0 lnd was in use on mynode for a while. For others to check if it's a macaroon missing permission issue, you can run this command:

lncli printmacaroon --macaroon_file /mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/admin.macaroon

**Comment by MWDJ** [comment]
LiT v0.9.0-alpha confirmed working (including lightning node connect) after deleting the admin.macaroon, invoice.macaroon, and readonly.macaroon files from /mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/
I verified the information was missing from the macaroons using the printmacaroon command @tehelsper 
Thank you @Eegee for linking everything! Extremely quick fix. 👍 

Hopefully this helps out @HamishMacEwan and @godSaysHODL to close this issue.
-DJ

**Comment by tehelsper** [comment]
@MWDJ Have you been running your node since 2019 or early 2020? The interesting thing about that fix is that it should have only occurred on _very_ old wallets.

**Comment by MWDJ** [comment]
Early 2020.... so agree a GUI method to manage, clean up, and regenerate macaroons would be a great feature!
-DJ

**Comment by Eegee** [comment]
My macaroon files were from June 1st 2020.

**Comment by tehelsper** [comment]
Full management would be a large undertaking, but perhaps I could add a regen macaroon option on the settings page. Did you only delete the macaroon files themselves or the macaroons.db file as well?

**Comment by MWDJ** [comment]
@tehelsper just the 3x macaroon files in the lnd mainnet directory.
"admin.macaroon, invoice.macaroon, and readonly.macaroon files from /mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/"
When LND restarts it regenerates the proper macaroon files with updated content.
I copied the old files just in case, but it worked immediately after a restart of all the related services.

**Comment by HamishMacEwan** [comment]
The 0.3.16 upgrade and careful revision of my customised `lnd.config` has resolved the problem.  Thanks to all of the encouragement from other sufferers.  I did perform the recommended actions and checked the macaroon values, to no avail.  It seemed to involve `rpcmiddleware` settings.

**Comment by Eegee** [comment]
> PS.
> 
> ```
> bitcoin@myNode:~ $ ls -ld .lnd /mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/
> lrwxrwxrwx 1 bitcoin bitcoin   19 Jun 19  2022 .lnd -> /mnt/hdd/mynode/lnd
> drwx--x--x 2 bitcoin bitcoin 4096 May  5 22:16 /mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/
> ```

Ah sorry, my bad, I hadn't noticed earlier you showed the path for the bitcoin user. 👍
for user admin it's a local folder.

**Comment by godSaysHODL** [comment]
is there a GUI button to implement the fix yet? I've updated to 0.3.16 and am reading through this thread, still not sure what to do.

**Comment by tehelsper** [comment]
I would also reset your custom lnd config and add you changes to the new "additional config" section.

To run commands, try this guide.

https://mynodebtc.github.io/advanced/linux-terminal.html

**Comment by godSaysHODL** [comment]
Update: resetting my config worked
